"""
docmind/modules/auth/protocols.py

Protocol definitions for auth service abstraction.
"""

from datetime import datetime
from typing import Protocol


class AuthServiceProtocol(Protocol):
    async def signup(self, email: str, password: str) -> dict: ...
    async def login(self, email: str, password: str) -> dict: ...
    async def logout(self, access_token: str) -> None: ...
    async def refresh(self, refresh_token: str) -> dict: ...
    async def get_user(self, access_token: str) -> dict: ...


class ApiTokenRepositoryProtocol(Protocol):
    async def create(self, user_id: str, name: str, prefix: str, hashed_secret: str, scopes: list[str], token_type: str, expires_at: datetime | None) -> object: ...
    async def get_by_prefix(self, prefix: str) -> object | None: ...
    async def list_for_user(self, user_id: str) -> list: ...
    async def get_by_id(self, token_id: str, user_id: str) -> object | None: ...
    async def revoke(self, token_id: str, user_id: str) -> bool: ...
    async def update(self, token_id: str, user_id: str, name: str | None, scopes: list[str] | None) -> object | None: ...
    async def update_last_used(self, token_id: str) -> None: ...


class ApiTokenServiceProtocol(Protocol):
    async def create_token(self, user_id: str, name: str, scopes: list[str], token_type: str, expires_in_days: int | None) -> dict: ...
    async def validate_token(self, raw_token: str) -> dict: ...
    async def list_tokens(self, user_id: str) -> list[dict]: ...
    async def revoke_token(self, token_id: str, user_id: str) -> bool: ...
    async def update_token(self, token_id: str, user_id: str, name: str | None, scopes: list[str] | None) -> dict: ...
