"""
docmind/modules/auth/protocols.py

Protocol definitions for auth service abstraction.
"""

from typing import Protocol


class AuthServiceProtocol(Protocol):
    async def signup(self, email: str, password: str) -> dict: ...
    async def login(self, email: str, password: str) -> dict: ...
    async def logout(self, access_token: str) -> None: ...
    async def refresh(self, refresh_token: str) -> dict: ...
    async def get_user(self, access_token: str) -> dict: ...
