"""Protocols for the analytics module — structural contracts for DI."""

from __future__ import annotations

from typing import Protocol


class AnalyticsRepositoryProtocol(Protocol):
    """Contract for analytics data queries."""

    async def count_documents(self, user_id: str) -> int: ...
    async def count_documents_by_status(self, user_id: str) -> dict[str, int]: ...
    async def count_documents_by_type(self, user_id: str) -> dict[str, int]: ...
    async def sum_pages(self, user_id: str) -> int: ...
    async def sum_storage_bytes(self, user_id: str) -> int: ...
    async def count_chunks(self, user_id: str) -> int: ...
    async def count_projects(self, user_id: str) -> int: ...
    async def count_custom_personas(self, user_id: str) -> int: ...


class AnalyticsServiceProtocol(Protocol):
    """Contract for analytics formatting."""

    def format_summary(self, **kwargs: object) -> dict: ...
